dateModified: 1769594317
email:
  fromEmail: joe@servd.host
  fromName: empty-project
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3cc0f0fe-b491-4abd-9c6e-b12850cbda65: empty-project # empty-project
    f4dfc012-666b-40b2-b2ef-9f08e9c878ed: empty-project # empty-project
system:
  edition: solo
  live: true
  name: empty-project
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
